In [26]:
import numpy as np

#converting a list to Array

In [30]:
lst=[1,2,3,4]
print(type(lst))
arr=np.array(lst)
print(type(arr))
arr=np.array(lst)
print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4]


In [32]:
#Arrange function
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [33]:
#Multidimensional Array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
#Size function

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Total : ', arr.size)
print('Row: ',np.size(arr,0))
print('Column: ',np.size(arr,1))

Total :  9
Row:  3
Column:  3


In [37]:
#Shape function

arr=np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
print((np.size(arr,0),np.size(arr,1)))
print(arr.shape)


(4, 3)
(4, 3)


In [41]:
#Dtype function
arr1=np.array([1,2,3,1,2,3])
arr2=np.array([1.2,2.3,3.1])
print(arr1.dtype)
print(arr2.dtype)

int64
float64


In [44]:
#Linspace function
#The numpy.linspace() function returns number spaces evenly w.r.t interval. 
#Similar to numpy.arange() function but instead of step it uses sample number.

np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [46]:
#Flatten function
#npdaaray.flatten() function return a copy of the array collapsed into 1D

arr=np.random.randint(1,15,(3,4))

print(arr.shape)
print(arr)
print('-'*20)
arr=arr.flatten()
print(arr.shape)
print(arr)

(3, 4)
[[ 7 12 14  4]
 [ 2  3 11  6]
 [ 6  3  8  1]]
--------------------
(12,)
[ 7 12 14  4  2  3 11  6  6  3  8  1]


In [48]:
#LogSpace function
#The np.logspace()  return no. spaces w.r.t interval on a log scale.

print(np.logspace(2,4,10))
print('-'*20)
print(np.logspace(2,4,10, base=2))

[  100.           166.81005372   278.25594022   464.15888336
   774.26368268  1291.54966501  2154.43469003  3593.8136638
  5994.84250319 10000.        ]
--------------------
[ 4.          4.66611616  5.44316     6.34960421  7.4069977   8.64047791
 10.0793684  11.75787594 13.71590373 16.        ]


In [50]:
#Copy function
#If we normally use the equals sign then the **id** of both the numpy array will be same, so we need to use to copy function

arr1=np.random.randint(1,15,10)
arr2=arr1
print(arr1,id(arr1))
print(arr2,id(arr2))
print('-'*50)
arr1=np.random.randint(1,15,10)
arr2=np.copy(arr1)
print(arr1, id(arr1))
print(arr2, id(arr2))


[ 7 10  2  5  7 14  9  2  9 14] 2009462912656
[ 7 10  2  5  7 14  9  2  9 14] 2009462912656
--------------------------------------------------
[ 4  6  7  4 12  5  5  1  3 14] 2009462913232
[ 4  6  7  4 12  5  5  1  3 14] 2009462914480


In [51]:
#arr.max(), arr.min(), arr.sum() functions
#we can get particular column and row sum using 
#axis=0 for column
#axis=1 for row

arr=np.random.randint(1,30,(3,5))
print('-'*20)
print(arr)
print('-'*20)

print('MAX: ',arr.max())
print('MIN: ',arr.min())
print('SUM: ',arr.sum())

--------------------
[[ 6 25  8 18 26]
 [ 6  3 29  3 12]
 [13 14  5 14 29]]
--------------------
MAX:  29
MIN:  3
SUM:  211


In [2]:
#seed function
#random() function is used to generate random numbers in Python. 
#Not actually random, rather this is used to generate pseudo-random numbers. 
#That implies that these randomly generated numbers can be determined. random() function generates numbers for some values. 
#This value is also called seed value.

#syntax: random.seed(l,version)<br>
#where l=any seed value used to product a random number
# and version=a Int used to specify how to convert l in a int
import numpy as np

np.random.seed(3)
arr=np.random.randint(1,10,(3,5))
arr




array([[9, 4, 9, 9, 1],
       [6, 4, 6, 8, 7],
       [1, 5, 8, 9, 2]], dtype=int32)

In [4]:
#sorting function
#return sorted copy of an array

np.random.seed(3)
arr = np.random.randint(1,10,(3,5))


print('-'*15)
print(arr)
print('-'*15)
print(np.sort(arr, axis = 1))
print('-'*15)
print(np.sort(arr, axis = 0))
print('-'*15)

arr = np.reshape(np.sort(arr.flatten()), arr.shape)
print(arr)
print('-'*15)

---------------
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[1 4 9 9 9]
 [4 6 6 7 8]
 [1 2 5 8 9]]
---------------
[[1 4 6 8 1]
 [6 4 8 9 2]
 [9 5 9 9 7]]
---------------
[[1 1 2 4 4]
 [5 6 6 7 8]
 [8 9 9 9 9]]
---------------


In [8]:
#Mathematical Operations

#---Addition---
print("ADDITION")
np.random.seed(3)
arr=np.random.randint(1,10,(3,5))
print('-' * 15)
print(arr)
print('-' * 15)
print(arr + 1)
print('-' * 15)

#--Substraction--
print("SUBSTRACTION")
print('-' * 15)
print(arr)
print('-' * 15)
print(arr - 1)
print('-' * 15)

#--Multiplication
print("MULTIPLICATION")
print('-' * 15)
print(arr)
print('-' * 15)
print(arr / 2)
print('-' * 15)

#--Power--
print("POWER")
print(arr)
print('-'*15)
print(arr ** 2)

ADDITION
---------------
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[10  5 10 10  2]
 [ 7  5  7  9  8]
 [ 2  6  9 10  3]]
---------------
SUBSTRACTION
---------------
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[8 3 8 8 0]
 [5 3 5 7 6]
 [0 4 7 8 1]]
---------------
MULTIPLICATION
---------------
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[4.5 2.  4.5 4.5 0.5]
 [3.  2.  3.  4.  3.5]
 [0.5 2.5 4.  4.5 1. ]]
---------------
POWER
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[81 16 81 81  1]
 [36 16 36 64 49]
 [ 1 25 64 81  4]]


In [10]:
#Percentile function
#used to compute the nth percentile of the given data along the specified axis

np.random.seed(3)
arr=np.random.randint(1,10,10)
print(arr)
arr=np.sort(arr)
print(arr)
print(np.percentile(arr,50))

[9 4 9 9 1 6 4 6 8 7]
[1 4 4 6 6 7 8 9 9 9]
6.5


In [11]:
#Mean, Variance, Standard Deviation
#used np.mean(), np.std(), np.var()
arr=np.random.randint(1,10,10)
print(arr)
print(arr.mean())
print(arr.var())
print(arr.std())


[1 5 8 9 2 7 3 3 2 4]
4.4
6.839999999999999
2.6153393661244038


In [12]:
#Filtering an numpy array
arr=np.arange(1,10)
print(arr)
print(arr<5)
print(arr[arr<5])

[1 2 3 4 5 6 7 8 9]
[ True  True  True  True False False False False False]
[1 2 3 4]


In [13]:
#Tranposing an array
arr=np.random.randint(1,20,(3,5))
print(arr)
print('-'*20)
print(arr.T)


[[ 6  9 15  2 11]
 [ 8 12  2 16 17]
 [ 6 18 15  1  1]]
--------------------
[[ 6  8  6]
 [ 9 12 18]
 [15  2 15]
 [ 2 16  1]
 [11 17  1]]


In [15]:
#where function
#return indices of elements in an input array where the given condition is satisfied

arr = np.random.randint(1,100,10)
arr
print('-'*20)
print(arr)
print(np.where(arr%2==0, 'even', arr))
print(np.where(arr%2==0, 'odd', arr))
arr1=np.where(arr%2==0, 'even', arr)
arr1=np.where(arr%2!=0, 'odd', arr1)
print(arr1)

--------------------
[86 75 92 17 81 33 17 19 76 56]
['even' '75' 'even' '17' '81' '33' '17' '19' 'even' 'even']
['odd' '75' 'odd' '17' '81' '33' '17' '19' 'odd' 'odd']
['even' 'odd' 'even' 'odd' 'odd' 'odd' 'odd' 'odd' 'even' 'even']


In [16]:
#Merging Arrays
arr1 = np.random.randint(1,10,(2,4))
arr2 = np.random.randint(1,10,(2,4))

print(arr1)
print('-'*15)
print(arr2)

print('-'*30)
print(np.concatenate((arr1,arr2), axis = 0))
print('-'*30)
print(np.concatenate((arr1,arr2), axis = 1))

[[1 6 1 2]
 [5 2 3 3]]
---------------
[[5 9 1 7]
 [1 5 2 6]]
------------------------------
[[1 6 1 2]
 [5 2 3 3]
 [5 9 1 7]
 [1 5 2 6]]
------------------------------
[[1 6 1 2 5 9 1 7]
 [5 2 3 3 1 5 2 6]]


In [19]:
#Vstack and Hstack
# these are used to stack the sequence of the input array horizontally  and vertically

arr1 = np.random.randint(1,10,(2,4))
arr2 = np.random.randint(1,10,(2,4))

print(arr1)
print('-'*15)
print(arr2)
print('-'*15)

print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

[[8 2 1 1]
 [6 9 5 9]]
---------------
[[9 4 5 3]
 [6 5 8 2]]
---------------
[[8 2 1 1 9 4 5 3]
 [6 9 5 9 6 5 8 2]]
[[8 2 1 1]
 [6 9 5 9]
 [9 4 5 3]
 [6 5 8 2]]


In [20]:
#Splitting Array
arr=np.random.randint(1,10,(4,4))
print(arr)

np.vsplit(arr,2)
np.hsplit(arr,2)

[[1 8 5 9]
 [9 5 2 5]
 [1 6 7 8]
 [1 8 9 2]]


[array([[1, 8],
        [9, 5],
        [1, 6],
        [1, 8]], dtype=int32),
 array([[5, 9],
        [2, 5],
        [7, 8],
        [9, 2]], dtype=int32)]

In [21]:
#Turning the pic into Numpy array

from matplotlib.image import imread

img = imread('GFG.png')

img.shape

(607, 1000, 3)